timedeplw – uDALES
timedeplw Subroutine
20 statements
Source File
private subroutine timedeplw()
Uses
modEB
modglobal
modmpi
Arguments
None
Called by
Source Code
  subroutine timedeplw
    use modglobal,    only : timee, skyLW, rk3step
    use modEB,        only : tnextEB
    use modmpi,       only : myid
    implicit none
    integer t,k
    real fac
    if(.not.(ltimedeplw)) return
    if ((rk3step .eq. 3) .and. (timee .ge. tnextEB)) then
    ! if (myid == 0) then
    !  write(*,*) "EB coming up so changing longwave forcing"
    ! end if
    !---- interpolate ----
    do t=ntimedeplw,1,-1
      if (timee .ge. timelw(t)) then
        exit
      endif
    end do
    if (t .ne. ntimedeplw) then
      fac = (timee - timelw(t)) / (timelw(t+1) - timelw(t))
      skyLW = skyLWt(t) + fac * (skyLWt(t+1) - skyLWt(t))
    end if
    end if
  end subroutine timedeplw
Call graph
timedep calls timedeplw
inittimedep calls timedep
dalesurban calls timedep, inittimedep