name: CI

on: [pull_request]

jobs:
  main:
    name: ${{ matrix.os }} ${{ matrix.build-type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'macos-14']
        build-type: ['Debug', 'Release']
        include:
          - os: macos-14
            FC: gfortran-12  # add the FC variable to macos runs
    defaults:
      run:
        # 'shell' required to activate environment.
        # See https://github.com/conda-incubator/setup-miniconda#IMPORTANT.
        shell: bash -el {0}
    steps:
    - name: Check-out project
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0  # get all branches

    - name: Install system dependencies
      run: bash .github/scripts/install_deps.sh

    - name: Install python dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: udales
        environment-file: environment.yml

    - name: Build and test uDALES
      run: |
        FC=${{ matrix.FC }} python3 -u tests/run_tests.py master $GITHUB_SHA ${{ matrix.build-type}}

    - name: Build docs
      if: matrix.os == 'ubuntu-22.04' && matrix.build-type == 'Release'
      run: |
        mkdocs build --site-dir build/html
        ford docs/udales-docs-software.md

    - name: Publish docs
      if: matrix.os == 'ubuntu-22.04' && matrix.build-type == 'Release' && github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html/
        force_orphan: true
