name: CI

on: [push, pull_request]

jobs:
  main:
    name: ${{ matrix.os }} ${{ matrix.build-type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        build-type: ['Debug', 'Release']
    
    steps:
    - name: Check-out project
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0  # get all branches

    - name: Install system dependencies
      run: bash .github/scripts/install_deps.sh

    - name: Install python dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: udales
        environment-file: environment.yml

    - name: Build and test uDALES
      # 'shell' required to activate environment.
      # See https://github.com/conda-incubator/setup-miniconda#IMPORTANT.
      shell: bash -l {0}
      run: |
        if [ ${{ matrix.os }} = 'macos-latest' ]; then export FC=gfortran-12; fi
        python3 -u tests/run_tests.py master $GITHUB_SHA ${{ matrix.build-type}}

    - name: Build docs
      if: matrix.os == 'ubuntu-latest' && matrix.build-type == 'Release'
      shell: bash -l {0}
      run: |
        mkdocs build --site-dir build/html
        ford docs/udales-docs-software.md

    - name: Publish docs
      if: matrix.os == 'ubuntu-latest' && matrix.build-type == 'Release' && github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html/
        force_orphan: true
